name: Sync Fork and Create PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch and Merge Upstream
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://github.com/debianio/stable.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories -m "Auto-merge upstream changes"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync with upstream"
          title: "🔄 Auto-Sync: Upstream Changes"
          body: "chore:( New changes from upstream repository. ) AUTO PR || exit 0 :)"
          branch: "auto-sync-upstream"
          base: "main"
